REACTIONS = [
    {"reactants": ["[Na]", "ClCl"], "products": ["[Na+][Cl-]"]},
    {"reactants": ["[Fe]", "ClCl"], "products": ["[Fe+3].[Cl-].[Cl-].[Cl-]"]},
    {"reactants": ["[Cu]", "ClCl"], "products": ["[Cu+2].[Cl-].[Cl-]"]},
    {"reactants": ["[K]", "ClCl"], "products": ["[K+][Cl-]"]},
    {"reactants": ["[Na]", "ClCl"], "products": ["[Na+][Cl-]"]},
    {"reactants": ["[Al]", "ClCl"], "products": ["[Al+3].[Cl-].[Cl-].[Cl-]"]},
    {"reactants": ["[Ca]", "ClCl"], "products": ["[Ca+2].[Cl-].[Cl-]"]},
    {"reactants": ["[Fe+2].[Cl-].[Cl-]", "ClCl"], "products": ["[Fe+3].[Cl-].[Cl-].[Cl-]"]},
    {"reactants": ["[H][H]", "ClCl"], "products": ["Cl"]},
    {"reactants": ["[Al]", "BrBr"], "products": ["[Al+3].[Br-].[Br-].[Br-]"]},
    {"reactants": ["[Al]", "II"], "products": ["[Al+3].[I-].[I-].[I-]"]},
    {"reactants": ["[H][H]", "BrBr"], "products": ["Br"]},
    {"reactants": ["[H][H]", "II"], "products": ["I"]},
    {"reactants": ["[H][H]", "FF"], "products": ["F"]},
    {"reactants": ["[Ca]", "O=O"], "products": ["[Ca+2][O-2]"]},
    {"reactants": ["[Al]", "O=O"], "products": ["[Al+3].[Al+3].[O-2].[O-2].[O-2]"]},
    {"reactants": ["[Fe]", "O=O"], "products": ["[Fe+3].[Fe+3].[O-2].[O-2].[O-2]"]},
    {"reactants": ["[Fe]", "O=O"], "products": ["[Fe+2].[Fe+3].[Fe+3].[O-2].[O-2].[O-2].[O-2]"]},
    {"reactants": ["[Fe]", "O=O"], "products": ["[Fe+2][O-2]"]},
    {"reactants": ["[Zn]", "O=O"], "products": ["[Zn+2][O-2]"]},
    {"reactants": ["[Cu]", "O=O"], "products": ["[Cu+2][O-2]"]},
    {"reactants": ["[Mg]", "O=O"], "products": ["[Mg+2][O-2]"]},
    {"reactants": ["[Na]", "O=O"], "products": ["[Na+].[Na+].[O-2]"]},
    {"reactants": ["[K]", "O=O"], "products": ["[K+].[K+].[O-2]"]},
    {"reactants": ["[S]", "O=O"], "products": ["O=S=O"]},
    {"reactants": ["O=S=O", "O=O"], "products": ["O=S(=O)=O"]},
    {"reactants": ["[C]", "O=O"], "products": ["O=C=O"]},
    {"reactants": ["N#N", "O=O"], "products": ["N=O"]},
    {"reactants": ["[H][H]", "O=O"], "products": ["O"]},
    {"reactants": ["[Fe]", "[S]"], "products": ["[Fe+2][S-2]"]},
    {"reactants": ["[Zn]", "[S]"], "products": ["[Zn+2][S-2]"]},
    {"reactants": ["[Cu]", "[S]"], "products": ["[Cu+2][S-2]"]},
    {"reactants": ["[Hg]", "[S]"], "products": ["[Hg+2][S-2]"]},
    {"reactants": ["[H][H]", "[S]"], "products": ["S"]},
    {"reactants": ["O=S=O", "[Ca+2][O-2]"], "products": ["[Ca+2][O-]S(=O)[O-]"]},
    {"reactants": ["O", "O=S=O"], "products": ["OS(O)O"]},
    {"reactants": ["O=S(=O)=O", "O"], "products": ["OS(=O)(=O)O"]},
    {"reactants": ["O=S=O", "O=O"], "products": ["O=S(=O)=O"]},
    {"reactants": ["O=S=O", "O"], "products": ["OS(O)O"]},
    {"reactants": ["O=S=O", "[Na+][OH-]"], "products": ["[Na+][O-]S(=O)O"]},
    {"reactants": ["N#N", "[H][H]"], "products": ["N"]},
    {
        "reactants": ["[Fe+3].[OH-].[OH-].[OH-]", "OS(=O)(=O)O"],
        "products": ["[Fe+3].[Fe+3].[O-]S(=O)(=O)[O-].[O-]S(=O)(=O)[O-].[O-]S(=O)(=O)[O-]", "O"],
    },
    {"reactants": ["ClCl", "O"], "products": ["Cl", "OCl"]},
    {"reactants": ["[Mn+4][O-2].[O-2]", "Cl"], "products": ["[Mn+2].[Cl-].[Cl-]", "ClCl", "O"]},
    {"reactants": ["Cl", "[K+][O-][Mn](=O)(=O)=O"], "products": ["[K+][Cl-]", "[Mn+2].[Cl-].[Cl-]", "O", "ClCl"]},
    {"reactants": ["[Na+][Cl-]", "O"], "products": ["ClCl", "[H][H]", "[Na+][OH-]"]},
    {"reactants": ["ClCl", "[K+][Br-]"], "products": ["[K+][Cl-]", "BrBr"]},
    {"reactants": ["ClCl", "[Na+][Br-]"], "products": ["[Na+][Cl-]", "BrBr"]},
    {"reactants": ["[Na+][Cl-]", "OS(=O)(=O)O"], "products": ["[Na+][O-]S(=O)(=O)O", "Cl"]},
    {"reactants": ["[K+][Cl-]", "OS(=O)(=O)O"], "products": ["[K+][O-]S(=O)(=O)O", "Cl"]},
    {"reactants": ["[K+][Cl-]", "OS(=O)(=O)O"], "products": ["[K+].[K+].[O-]S(=O)(=O)[O-]", "Cl"]},
    {"reactants": ["[Ca+2].[Cl-].[Cl-]", "OS(=O)(=O)O"], "products": ["[Ca+2][O-]S(=O)(=O)[O-]", "Cl"]},
    {"reactants": ["[Ca+2].[Cl-].[Cl-]", "OS(=O)(=O)O"], "products": ["[Ca+2].[O-]S(=O)(=O)O.[O-]S(=O)(=O)O", "Cl"]},
    {"reactants": ["[Zn]", "Cl"], "products": ["[Zn+2].[Cl-].[Cl-]", "[H][H]"]},
    {"reactants": ["[Fe]", "Cl"], "products": ["[Fe+2].[Cl-].[Cl-]", "[H][H]"]},
    {"reactants": ["[Al]", "Cl"], "products": ["[Al+3].[Cl-].[Cl-].[Cl-]", "[H][H]"]},
    {"reactants": ["[Ca]", "Cl"], "products": ["[Ca+2].[Cl-].[Cl-]", "[H][H]"]},
    {"reactants": ["[Na]", "Cl"], "products": ["[Na+][Cl-]", "[H][H]"]},
    {"reactants": ["[K]", "Cl"], "products": ["[K+][Cl-]", "[H][H]"]},
    {"reactants": ["[Mg]", "Cl"], "products": ["[Mg+2].[Cl-].[Cl-]", "[H][H]"]},
    {"reactants": ["[Cu+2][O-2]", "Cl"], "products": ["[Cu+2].[Cl-].[Cl-]", "O"]},
    {"reactants": ["[Zn+2][O-2]", "Cl"], "products": ["[Zn+2].[Cl-].[Cl-]", "O"]},
    {"reactants": ["[Mg+2][O-2]", "Cl"], "products": ["[Mg+2].[Cl-].[Cl-]", "O"]},
    {"reactants": ["[Mn+4][O-2].[O-2]", "Cl"], "products": ["[Mn+2].[Cl-].[Cl-]", "ClCl", "O"]},
    {"reactants": ["[Al+3].[Al+3].[O-2].[O-2].[O-2]", "Cl"], "products": ["[Al+3].[Cl-].[Cl-].[Cl-]", "O"]},
    {"reactants": ["[Al+3].[OH-].[OH-].[OH-]", "Cl"], "products": ["[Al+3].[Cl-].[Cl-].[Cl-]", "O"]},
    {"reactants": ["[Na+][OH-]", "Cl"], "products": ["[Na+][Cl-]", "O"]},
    {"reactants": ["[K+][OH-]", "Cl"], "products": ["[K+][Cl-]", "O"]},
    {"reactants": ["[Zn+2].[OH-].[OH-]", "Cl"], "products": ["[Zn+2].[Cl-].[Cl-]", "O"]},
    {"reactants": ["[Cu+2].[OH-].[OH-]", "Cl"], "products": ["[Cu+2].[Cl-].[Cl-]", "O"]},
    {"reactants": ["ClCl", "[K+][OH-]"], "products": ["[K+][O-]Cl(=O)=O", "[K+][Cl-]", "O"]},
    {"reactants": ["ClCl", "[Na+][OH-]"], "products": ["[Na+][O-]Cl", "[Na+][Cl-]", "O"]},
    {"reactants": ["[Ag+][O-][N+](=O)[O-]", "Cl"], "products": ["O[N+](=O)[O-]", "[Ag+][Cl-]"]},
    {"reactants": ["[Ca+2][O-]C(=O)[O-]", "Cl"], "products": ["[Ca+2].[Cl-].[Cl-]", "O", "O=C=O"]},
    {"reactants": ["[Mg+2][O-]C(=O)[O-]", "Cl"], "products": ["[Mg+2].[Cl-].[Cl-]", "O", "O=C=O"]},
    {"reactants": ["[Ba+2][O-]S(=O)[O-]", "Cl"], "products": ["[Ba+2].[Cl-].[Cl-]", "OS(O)O"]},
    {"reactants": ["[Ag+][O-][N+](=O)[O-]", "[Na+][Cl-]"], "products": ["[Na+][O-][N+](=O)[O-]", "[Ag+][Cl-]"]},
    {"reactants": ["[Ag+][O-][N+](=O)[O-]", "[K+][Cl-]"], "products": ["[K+][O-][N+](=O)[O-]", "[Ag+][Cl-]"]},
    {"reactants": ["S", "[O-]Cl(=O)=O"], "products": ["Cl", "OS(=O)(=O)O"]},
    {"reactants": ["ClCl", "[Na+][OH-]"], "products": ["[Na+][Cl-]", "[Na+][O-]Cl", "O"]},
    {"reactants": ["ClCl", "[K+][OH-]"], "products": ["[K+][Cl-]", "[K+][O-]Cl", "O"]},
    {"reactants": ["ClCl", "[K+][OH-]"], "products": ["[K+][Cl-]", "[K+][O-]Cl(=O)=O", "O"]},
    {"reactants": ["[Ca+2].[OH-].[OH-]", "ClCl"], "products": ["[Ca+2][O-][Cl-][Cl-]", "O"]},
    {"reactants": ["BrBr", "[Na+][I-]"], "products": ["[Na+][Br-]", "II"]},
    {"reactants": ["ClCl", "[Na+][Br-]"], "products": ["[Na+][Cl-]", "BrBr"]},
    {"reactants": ["O=[Si]=O", "F"], "products": ["F[Si](F)(F)F", "O"]},
    {"reactants": ["FF", "O"], "products": ["F", "O=O"]},
    {"reactants": ["N", "O=O"], "products": ["N=O", "O"]},
    {"reactants": ["S", "O=O"], "products": ["O=S=O", "O"]},
    {"reactants": ["S", "O=O"], "products": ["[S]", "O"]},
    {"reactants": ["S", "[Cu+2][O-]S(=O)(=O)[O-]"], "products": ["[Cu+2][S-2]", "OS(=O)(=O)O"]},
    {"reactants": ["[Fe+2][S-2]", "Cl"], "products": ["[Fe+2].[Cl-].[Cl-]", "S"]},
    {"reactants": ["[Zn+2][S-2]", "Cl"], "products": ["[Zn+2].[Cl-].[Cl-]", "S"]},
    {"reactants": ["O=S=O", "[Na+][OH-]"], "products": ["[Na+].[Na+].[O-]S(=O)[O-]", "O"]},
    {"reactants": ["S", "O=S=O"], "products": ["[S]", "O"]},
    {"reactants": ["[Fe+2][S-][S-]", "O=O"], "products": ["[Fe+3].[Fe+3].[O-2].[O-2].[O-2]", "O=S=O"]},
    {"reactants": ["[Zn+2][S-2]", "O=O"], "products": ["[Zn+2][O-2]", "O=S=O"]},
    {"reactants": ["[Cu+2][S-2]", "O=O"], "products": ["[Cu+2][O-2]", "O=S=O"]},
    {"reactants": ["[Na+][OH-]", "OS(=O)(=O)O"], "products": ["[Na+].[Na+].[O-]S(=O)(=O)[O-]", "O"]},
    {"reactants": ["[K+][OH-]", "OS(=O)(=O)O"], "products": ["[K+].[K+].[O-]S(=O)(=O)[O-]", "O"]},
    {"reactants": ["[Ba+2].[OH-].[OH-]", "OS(=O)(=O)O"], "products": ["[Ba+2][O-]S(=O)(=O)[O-]", "O"]},
    {"reactants": ["[Mg+2].[OH-].[OH-]", "OS(=O)(=O)O"], "products": ["[Mg+2][O-]S(=O)(=O)[O-]", "O"]},
    {"reactants": ["[Cu+2][O-2]", "OS(=O)(=O)O"], "products": ["[Cu+2][O-]S(=O)(=O)[O-]", "O"]},
    {"reactants": ["[Zn+2][O-2]", "OS(=O)(=O)O"], "products": ["[Zn+2][O-]S(=O)(=O)[O-]", "O"]},
    {"reactants": ["[Zn]", "OS(=O)(=O)O"], "products": ["[Zn+2][O-]S(=O)(=O)[O-]", "[H][H]"]},
    {"reactants": ["[Fe]", "OS(=O)(=O)O"], "products": ["[Fe+2][O-]S(=O)(=O)[O-]", "[H][H]"]},
    {"reactants": ["[Na]", "OS(=O)(=O)O"], "products": ["[Na+].[Na+].[O-]S(=O)(=O)[O-]", "[H][H]"]},
    {"reactants": ["[K]", "OS(=O)(=O)O"], "products": ["[K+].[K+].[O-]S(=O)(=O)[O-]", "[H][H]"]},
    {"reactants": ["[Cu]", "OS(=O)(=O)O"], "products": ["[Cu+2][O-]S(=O)(=O)[O-]", "O=S=O", "O"]},
    {"reactants": ["[Mg]", "OS(=O)(=O)O"], "products": ["[Mg+2][O-]S(=O)(=O)[O-]", "[S]", "O"]},
    {"reactants": ["[C]", "OS(=O)(=O)O"], "products": ["O=C=O", "O=S=O", "O"]},
    {"reactants": ["[Ca+2][O-]C(=O)[O-]", "OS(=O)(=O)O"], "products": ["[Ca+2][O-]S(=O)(=O)[O-]", "O", "O=C=O"]},
    {"reactants": ["[K+].[K+].[O-]C(=O)[O-]", "OS(=O)(=O)O"], "products": ["[K+].[K+].[O-]S(=O)(=O)[O-]", "O", "O=C=O"]},
    {"reactants": ["OS(=O)(=O)O", "S"], "products": ["[S]", "O=S=O", "O"]},
    {"reactants": ["OS(=O)(=O)O", "[Ba+2].[Cl-].[Cl-]"], "products": ["[Ba+2][O-]S(=O)(=O)[O-]", "Cl"]},
    {"reactants": ["[Na+].[Na+].[O-]S(=O)(=O)[O-]", "[Ba+2].[Cl-].[Cl-]"], "products": ["[Ba+2][O-]S(=O)(=O)[O-]", "[Na+][Cl-]"]},
    {"reactants": ["[Na+].[Na+].[O-]S(=O)[O-]", "[Ba+2].[Cl-].[Cl-]"], "products": ["[Ba+2][O-]S(=O)[O-]", "[Na+][Cl-]"]},
    {"reactants": ["[K+].[K+].[O-]S(=O)(=O)[O-]", "[Ba+2].[Cl-].[Cl-]"], "products": ["[Ba+2][O-]S(=O)(=O)[O-]", "[K+][Cl-]"]},
    {"reactants": ["[K+].[K+].[O-]S(=O)[O-]", "[Ba+2].[Cl-].[Cl-]"], "products": ["[Ba+2][O-]S(=O)[O-]", "[K+][Cl-]"]},
    {"reactants": ["[Na+].[Na+].[O-]S(=O)(=O)[O-]", "[K+][Cl-]"], "products": ["[K+].[K+].[O-]S(=O)(=O)[O-]", "[Na+][Cl-]"]},
    {"reactants": ["[Fe]", "[Cu+2][O-]S(=O)(=O)[O-]"], "products": ["[Fe+2][O-]S(=O)(=O)[O-]", "[Cu]"]},
    {"reactants": ["[Zn]", "[Cu+2][O-]S(=O)(=O)[O-]"], "products": ["[Zn+2][O-]S(=O)(=O)[O-]", "[Cu]"]},
    {"reactants": ["[Cu+2][O-]S(=O)(=O)[O-]", "[K+][OH-]"], "products": ["[Cu+2].[OH-].[OH-]", "[K+].[K+].[O-]S(=O)(=O)[O-]"]},
    {"reactants": ["[Cu+2][O-]S(=O)(=O)[O-]", "[Na+][OH-]"], "products": ["[Cu+2].[OH-].[OH-]", "[Na+].[Na+].[O-]S(=O)(=O)[O-]"]},
    {"reactants": ["[Zn]", "OS(=O)(=O)O"], "products": ["[Zn+2][O-]S(=O)(=O)[O-]", "[S]", "O"]},
    {"reactants": ["[Mg]", "OS(=O)(=O)O"], "products": ["[Mg+2][O-]S(=O)(=O)[O-]", "S", "O"]},
    {"reactants": ["[Ag]", "OS(=O)(=O)O"], "products": ["[Ag+].[Ag+].[O-]S(=O)(=O)[O-]", "O=S=O", "O"]},
    {"reactants": ["[S]", "OS(=O)(=O)O"], "products": ["O=S=O", "O"]},
    {"reactants": ["[Fe+2][S-][S-]", "O=O"], "products": ["[Fe+3].[Fe+3].[O-2].[O-2].[O-2]", "O=S=O"]},
    {"reactants": ["[Na+].[Na+].[O-]S(=O)[O-]", "OS(=O)(=O)O"], "products": ["[Na+].[Na+].[O-]S(=O)(=O)[O-]", "O", "O=S=O"]},
    {"reactants": ["[Na+].[Na+].[O-]C(=O)[O-]", "OS(=O)(=O)O"], "products": ["[Na+].[Na+].[O-]S(=O)(=O)[O-]", "O", "O=C=O"]},
    {"reactants": ["[H][H]", "[Cu+2][O-2]"], "products": ["[Cu]", "O"]},
    {"reactants": ["[H][H]", "[Zn+2][O-2]"], "products": ["[Zn]", "O"]},
    {"reactants": ["[Fe+3].[Fe+3].[O-2].[O-2].[O-2]", "[H][H]"], "products": ["[Fe]", "O"]},
    {"reactants": ["[Zn+2].[OH-].[OH-]", "Cl"], "products": ["[Zn+2].[Cl-].[Cl-]", "O"]},
    {"reactants": ["[Cu+2].[OH-].[OH-]", "O[N+](=O)[O-]"], "products": ["[Cu+2].[O-][N+](=O)[O-].[O-][N+](=O)[O-]", "O"]},
    {"reactants": ["[C]", "[Cu+2][O-2]"], "products": ["[Cu]", "O=C=O"]},
    {"reactants": ["[C]", "O"], "products": ["[C]=O", "[H][H]"]},
    {"reactants": ["[C]", "O"], "products": ["O=C=O", "[H][H]"]},
    {"reactants": ["[Al]", "O"], "products": ["[Al+3].[OH-].[OH-].[OH-]", "[H][H]"]},
    {"reactants": ["[Al]", "[Fe+3].[Fe+3].[O-2].[O-2].[O-2]"], "products": ["[Al+3].[Al+3].[O-2].[O-2].[O-2]", "[Fe]"]},
    {"reactants": ["[Al+3].[Al+3].[O-2].[O-2].[O-2]", "[Na+][OH-]"], "products": ["[Na+][O-][Al+3][O-]", "O"]},
    {"reactants": ["[Al+3].[OH-].[OH-].[OH-]", "[Na+][OH-]"], "products": ["[Na+][O-][Al+3][O-]", "O"]},
    {"reactants": ["[Ca]", "O"], "products": ["[Ca+2].[OH-].[OH-]", "[H][H]"]},
    {"reactants": ["[Ca]", "O[N+](=O)[O-]"], "products": ["[Ca+2].[O-][N+](=O)[O-].[O-][N+](=O)[O-]", "[NH4+][O-][N+](=O)[O-]", "O"]},
    {"reactants": ["[Na]", "O"], "products": ["[Na+][OH-]", "[H][H]"]},
    {"reactants": ["[Na+][I-]", "BrBr"], "products": ["[Na+][Br-]", "II"]},
    {"reactants": ["[K+][I-]", "BrBr"], "products": ["[K+][Br-]", "II"]},
    {"reactants": ["[Fe]", "O"], "products": ["[Fe+2].[Fe+3].[Fe+3].[O-2].[O-2].[O-2].[O-2]", "[H][H]"]},
    {"reactants": ["[Fe]", "O"], "products": ["[Fe+2][O-2]", "[H][H]"]},
    {"reactants": ["[Fe]", "O[N+](=O)[O-]"], "products": ["[Fe+3].[O-][N+](=O)[O-].[O-][N+](=O)[O-].[O-][N+](=O)[O-]", "[N]=N=O", "O"]},
    {"reactants": ["[Fe+3].[OH-].[OH-].[OH-]", "O[N+](=O)[O-]"], "products": ["[Fe+3].[O-][N+](=O)[O-].[O-][N+](=O)[O-].[O-][N+](=O)[O-]", "O"]},
    {"reactants": ["O=C=O", "[Ca+2].[OH-].[OH-]"], "products": ["[Ca+2][O-]C(=O)[O-]", "O"]},
    {"reactants": ["O=[N+]([O-])", "[Na+][OH-]"], "products": ["[Na+][O-][N+]=O", "[Na+][O-][N+]=O", "O"]},
    {"reactants": ["[Na+][Cl-]", "OS(=O)(=O)O"], "products": ["[Na+].[Na+].[O-]S(=O)(=O)[O-]", "Cl"]},
    {"reactants": ["S", "[Pb+2].[O-][N+](=O)[O-].[O-][N+](=O)[O-]"], "products": ["[Pb+2][S-2]", "O[N+](=O)[O-]"]},
    {"reactants": ["[Na+].[Na+].[S-2]", "[Pb+2].[O-][N+](=O)[O-].[O-][N+](=O)[O-]"], "products": ["[Pb+2][S-2]", "[Na+][O-][N+](=O)[O-]"]},
    {"reactants": ["[K+][O-][N+](=O)[O-]", "[S]", "[C]"], "products": ["[K+].[K+].[S-2]", "N#N", "O=C=O"]},
    {"reactants": ["S", "ClCl", "O"], "products": ["OS(=O)(=O)O", "Cl"]},
    {"reactants": ["OS(O)O", "ClCl", "O"], "products": ["OS(=O)(=O)O", "Cl"]},
    {"reactants": ["OS(O)O", "BrBr", "O"], "products": ["OS(=O)(=O)O", "Br"]},
    {"reactants": ["[Fe]", "O", "O=O"], "products": ["[Fe+3].[OH-].[OH-].[OH-]"]},
    {
        "reactants": ["[Fe+2][O-]S(=O)(=O)[O-]", "[K+][O-][Mn](=O)(=O)=O", "OS(=O)(=O)O"],
        "products": [
            "[Fe+3].[Fe+3].[O-]S(=O)(=O)[O-].[O-]S(=O)(=O)[O-].[O-]S(=O)(=O)[O-]",
            "[Mn+2][O-]S(=O)(=O)[O-]",
            "[K+].[K+].[O-]S(=O)(=O)[O-]",
            "O",
        ],
    },
    {"reactants": ["[K+][O-]Cl(=O)=O"], "products": ["[K+][Cl-]", "O=O"]},
    {"reactants": ["[K+][O-]Cl(=O)=O"], "products": ["[K+][Cl-]", "[K+][O-]Cl(=O)(=O)=O"]},
    {"reactants": ["I"], "products": ["[H][H]", "II"]},
    {"reactants": ["[K+][O-]Cl(=O)=O"], "products": ["[K+][Cl-]", "O=O"]},
    {"reactants": ["[K+][O-][Mn](=O)(=O)=O"], "products": ["[K+].[K+].[O-][Mn](=O)(=O)[O-]", "[Mn+4][O-2].[O-2]", "O=O"]},
    {"reactants": ["O"], "products": ["[H][H]", "O=O"]},
    {"reactants": ["[Ba+2].[O-][N+](=O)[O-].[O-][N+](=O)[O-]", "OS(=O)(=O)O"], "products": ["[Ba+2][O-]S(=O)(=O)[O-]", "O[N+](=O)[O-]"]},
    {"reactants": ["[Ca+2][O-]C(=O)[O-]"], "products": ["[Ca+2][O-2]", "O=C=O"]},
    {"reactants": ["[Na+][O-][N+](=O)[O-]"], "products": ["[Na+][O-][N+]=O", "O=O"]},
    {"reactants": ["[Al+3].[Al+3].[O-2].[O-2].[O-2]"], "products": ["[Al]", "O=O"]},
    {"reactants": ["[Al+3].[OH-].[OH-].[OH-]"], "products": ["[Al+3].[Al+3].[O-2].[O-2].[O-2]", "O"]},
    {"reactants": ["[Ca+2].[Cl-].[Cl-]"], "products": ["[Ca]", "ClCl"]},
    {"reactants": ["[Na+][Cl-]"], "products": ["[Na]", "ClCl"]},
    {"reactants": ["[Na+][OH-]"], "products": ["[Na]", "O=O", "O"]},
    {"reactants": ["[NH4+].[NH4+].[O-]S(=O)(=O)[O-]"], "products": ["N", "OS(=O)(=O)O"]},
    {"reactants": ["[K+][O-][Mn](=O)(=O)=O"], "products": ["[K+].[K+].[O-][Mn](=O)(=O)[O-]", "[Mn+4][O-2].[O-2]", "O=O"]},
    {"reactants": ["O[N+](=O)[O-]"], "products": ["O=[N+]([O-])", "O=O", "O"]},
    {"reactants": ["[NH4+][O-][N+]=O"], "products": ["N#N", "O"]},
    {"reactants": ["[NH4+][O-][N+](=O)[O-]"], "products": ["N#N", "O=O", "O"]},
]
