REACTIONS = [
    {"reactants": ["Na", "Cl2"], "products": ["NaCl"]},
    {"reactants": ["Fe", "Cl2"], "products": ["FeCl3"]},
    {"reactants": ["Cu", "Cl2"], "products": ["CuCl2"]},
    {"reactants": ["K", "Cl2"], "products": ["KCl"]},
    {"reactants": ["Na", "Cl2"], "products": ["NaCl"]},
    {"reactants": ["Al", "Cl2"], "products": ["AlCl3"]},
    {"reactants": ["Ca", "Cl2"], "products": ["CaCl2"]},
    {"reactants": ["FeCl2", "Cl2"], "products": ["FeCl3"]},
    {"reactants": ["H2", "Cl2"], "products": ["HCl"]},
    {"reactants": ["Al", "Br2"], "products": ["AlBr3"]},
    {"reactants": ["Al", "I2"], "products": ["AlI3"]},
    {"reactants": ["H2", "Br2"], "products": ["HBr"]},
    {"reactants": ["H2", "I2"], "products": ["HI"]},
    {"reactants": ["H2", "F2"], "products": ["HF"]},
    {"reactants": ["Ca", "O2"], "products": ["CaO"]},
    {"reactants": ["Al", "O2"], "products": ["Al2O3"]},
    {"reactants": ["Fe", "O2"], "products": ["Fe2O3"]},
    {"reactants": ["Fe", "O2"], "products": ["Fe3O4"]},
    {"reactants": ["Fe", "O2"], "products": ["FeO"]},
    {"reactants": ["Zn", "O2"], "products": ["ZnO"]},
    {"reactants": ["Cu", "O2"], "products": ["CuO"]},
    {"reactants": ["Mg", "O2"], "products": ["MgO"]},
    {"reactants": ["Na", "O2"], "products": ["Na2O"]},
    {"reactants": ["K", "O2"], "products": ["K2O"]},
    {"reactants": ["S", "O2"], "products": ["SO2"]},
    {"reactants": ["SO2", "O2"], "products": ["SO3"]},
    {"reactants": ["C", "O2"], "products": ["CO2"]},
    {"reactants": ["N2", "O2"], "products": ["NO"]},
    {"reactants": ["H2", "O2"], "products": ["H2O"]},
    {"reactants": ["Fe", "S"], "products": ["FeS"]},
    {"reactants": ["Zn", "S"], "products": ["ZnS"]},
    {"reactants": ["Cu", "S"], "products": ["CuS"]},
    {"reactants": ["Hg", "S"], "products": ["HgS"]},
    {"reactants": ["H2", "S"], "products": ["H2S"]},
    {"reactants": ["SO2", "CaO"], "products": ["CaSO3"]},
    {"reactants": ["H2O", "SO2"], "products": ["H2SO3"]},
    {"reactants": ["SO3", "H2O"], "products": ["H2SO4"]},
    {"reactants": ["SO2", "O2"], "products": ["SO3"]},
    {"reactants": ["SO2", "H2O"], "products": ["H2SO3"]},
    {"reactants": ["SO2", "NaOH"], "products": ["NaHSO3"]},
    {"reactants": ["N2", "H2"], "products": ["NH3"]},
    {"reactants": ["Fe(OH)3", "H2SO4"], "products": ["Fe2(SO4)3", "H2O"]},
    {"reactants": ["Cl2", "H2O"], "products": ["HCl", "HClO"]},
    {"reactants": ["MnO2", "HCl"], "products": ["MnCl2", "Cl2", "H2O"]},
    {"reactants": ["HCl", "KMnO4"], "products": ["KCl", "MnCl2", "H2O", "Cl2"]},
    {"reactants": ["NaCl", "H2O"], "products": ["Cl2", "H2", "NaOH"]},
    {"reactants": ["Cl2", "KBr"], "products": ["KCl", "Br2"]},
    {"reactants": ["Cl2", "NaBr"], "products": ["NaCl", "Br2"]},
    {"reactants": ["NaCl", "H2SO4"], "products": ["NaHSO4", "HCl"]},
    {"reactants": ["KCl", "H2SO4"], "products": ["KHSO4", "HCl"]},
    {"reactants": ["KCl", "H2SO4"], "products": ["K2SO4", "HCl"]},
    {"reactants": ["CaCl2", "H2SO4"], "products": ["CaSO4", "HCl"]},
    {"reactants": ["CaCl2", "H2SO4"], "products": ["Ca(HSO4)2", "HCl"]},
    {"reactants": ["Zn", "HCl"], "products": ["ZnCl2", "H2"]},
    {"reactants": ["Fe", "HCl"], "products": ["FeCl2", "H2"]},
    {"reactants": ["Al", "HCl"], "products": ["AlCl3", "H2"]},
    {"reactants": ["Ca", "HCl"], "products": ["CaCl2", "H2"]},
    {"reactants": ["Na", "HCl"], "products": ["NaCl", "H2"]},
    {"reactants": ["K", "HCl"], "products": ["KCl", "H2"]},
    {"reactants": ["Mg", "HCl"], "products": ["MgCl2", "H2"]},
    {"reactants": ["CuO", "HCl"], "products": ["CuCl2", "H2O"]},
    {"reactants": ["ZnO", "HCl"], "products": ["ZnCl2", "H2O"]},
    {"reactants": ["MgO", "HCl"], "products": ["MgCl2", "H2O"]},
    {"reactants": ["MnO2", "HCl"], "products": ["MnCl2", "Cl2", "H2O"]},
    {"reactants": ["Al2O3", "HCl"], "products": ["AlCl3", "H2O"]},
    {"reactants": ["Al(OH)3", "HCl"], "products": ["AlCl3", "H2O"]},
    {"reactants": ["NaOH", "HCl"], "products": ["NaCl", "H2O"]},
    {"reactants": ["KOH", "HCl"], "products": ["KCl", "H2O"]},
    {"reactants": ["Zn(OH)2", "HCl"], "products": ["ZnCl2", "H2O"]},
    {"reactants": ["Cu(OH)2", "HCl"], "products": ["CuCl2", "H2O"]},
    {"reactants": ["Cl2", "KOH"], "products": ["KClO3", "KCl", "H2O"]},
    {"reactants": ["Cl2", "NaOH"], "products": ["NaClO", "NaCl", "H2O"]},
    {"reactants": ["AgNO3", "HCl"], "products": ["HNO3", "AgCl"]},
    {"reactants": ["CaCO3", "HCl"], "products": ["CaCl2", "H2O", "CO2"]},
    {"reactants": ["MgCO3", "HCl"], "products": ["MgCl2", "H2O", "CO2"]},
    {"reactants": ["BaSO3", "HCl"], "products": ["BaCl2", "H2SO3"]},
    {"reactants": ["AgNO3", "NaCl"], "products": ["NaNO3", "AgCl"]},
    {"reactants": ["AgNO3", "KCl"], "products": ["KNO3", "AgCl"]},
    {"reactants": ["H2S", "HClO3"], "products": ["HCl", "H2SO4"]},
    {"reactants": ["Cl2", "NaOH"], "products": ["NaCl", "NaClO", "H2O"]},
    {"reactants": ["Cl2", "KOH"], "products": ["KCl", "KClO", "H2O"]},
    {"reactants": ["Cl2", "KOH"], "products": ["KCl", "KClO3", "H2O"]},
    {"reactants": ["Ca(OH)2", "Cl2"], "products": ["CaOCl2", "H2O"]},
    {"reactants": ["Br2", "NaI"], "products": ["NaBr", "I2"]},
    {"reactants": ["Cl2", "NaBr"], "products": ["NaCl", "Br2"]},
    {"reactants": ["SiO2", "HF"], "products": ["SiF4", "H2O"]},
    {"reactants": ["F2", "H2O"], "products": ["HF", "O2"]},
    {"reactants": ["NH3", "O2"], "products": ["NO", "H2O"]},
    {"reactants": ["H2S", "O2"], "products": ["SO2", "H2O"]},
    {"reactants": ["H2S", "O2"], "products": ["S", "H2O"]},
    {"reactants": ["H2S", "CuSO4"], "products": ["CuS", "H2SO4"]},
    {"reactants": ["FeS", "HCl"], "products": ["FeCl2", "H2S"]},
    {"reactants": ["ZnS", "HCl"], "products": ["ZnCl2", "H2S"]},
    {"reactants": ["SO2", "NaOH"], "products": ["Na2SO3", "H2O"]},
    {"reactants": ["H2S", "SO2"], "products": ["S", "H2O"]},
    {"reactants": ["FeS2", "O2"], "products": ["Fe2O3", "SO2"]},
    {"reactants": ["ZnS", "O2"], "products": ["ZnO", "SO2"]},
    {"reactants": ["CuS", "O2"], "products": ["CuO", "SO2"]},
    {"reactants": ["NaOH", "H2SO4"], "products": ["Na2SO4", "H2O"]},
    {"reactants": ["KOH", "H2SO4"], "products": ["K2SO4", "H2O"]},
    {"reactants": ["Ba(OH)2", "H2SO4"], "products": ["BaSO4", "H2O"]},
    {"reactants": ["Mg(OH)2", "H2SO4"], "products": ["MgSO4", "H2O"]},
    {"reactants": ["CuO", "H2SO4"], "products": ["CuSO4", "H2O"]},
    {"reactants": ["ZnO", "H2SO4"], "products": ["ZnSO4", "H2O"]},
    {"reactants": ["Zn", "H2SO4"], "products": ["ZnSO4", "H2"]},
    {"reactants": ["Fe", "H2SO4"], "products": ["FeSO4", "H2"]},
    {"reactants": ["Na", "H2SO4"], "products": ["Na2SO4", "H2"]},
    {"reactants": ["K", "H2SO4"], "products": ["K2SO4", "H2"]},
    {"reactants": ["Cu", "H2SO4"], "products": ["CuSO4", "SO2", "H2O"]},
    {"reactants": ["Mg", "H2SO4"], "products": ["MgSO4", "S", "H2O"]},
    {"reactants": ["C", "H2SO4"], "products": ["CO2", "SO2", "H2O"]},
    {"reactants": ["CaCO3", "H2SO4"], "products": ["CaSO4", "H2O", "CO2"]},
    {"reactants": ["K2CO3", "H2SO4"], "products": ["K2SO4", "H2O", "CO2"]},
    {"reactants": ["H2SO4", "H2S"], "products": ["S", "SO2", "H2O"]},
    {"reactants": ["H2SO4", "BaCl2"], "products": ["BaSO4", "HCl"]},
    {"reactants": ["Na2SO4", "BaCl2"], "products": ["BaSO4", "NaCl"]},
    {"reactants": ["Na2SO3", "BaCl2"], "products": ["BaSO3", "NaCl"]},
    {"reactants": ["K2SO4", "BaCl2"], "products": ["BaSO4", "KCl"]},
    {"reactants": ["K2SO3", "BaCl2"], "products": ["BaSO3", "Kcl"]},
    {"reactants": ["Na2SO4", "KCl"], "products": ["K2SO4", "NaCl"]},
    {"reactants": ["Fe", "CuSO4"], "products": ["FeSO4", "Cu"]},
    {"reactants": ["Zn", "CuSO4"], "products": ["ZnSO4", "Cu"]},
    {"reactants": ["CuSO4", "KOH"], "products": ["Cu(OH)2", "K2SO4"]},
    {"reactants": ["CuSO4", "NaOH"], "products": ["Cu(OH)2", "Na2SO4"]},
    {"reactants": ["Zn", "H2SO4"], "products": ["ZnSO4", "S", "H2O"]},
    {"reactants": ["Mg", "H2SO4"], "products": ["MgSO4", "H2S", "H2O"]},
    {"reactants": ["Ag", "H2SO4"], "products": ["Ag2SO4", "SO2", "H2O"]},
    {"reactants": ["S", "H2SO4"], "products": ["SO2", "H2O"]},
    {"reactants": ["FeS2", "O2"], "products": ["Fe2O3", "SO2"]},
    {"reactants": ["Na2SO3", "H2SO4"], "products": ["Na2SO4", "H2O", "SO2"]},
    {"reactants": ["Na2CO3", "H2SO4"], "products": ["Na2SO4", "H2O", "CO2"]},
    {"reactants": ["H2", "CuO"], "products": ["Cu", "H2O"]},
    {"reactants": ["H2", "ZnO"], "products": ["Zn", "H2O"]},
    {"reactants": ["Fe2O3", "H2"], "products": ["Fe", "H2O"]},
    {"reactants": ["Zn(OH)2", "HCl"], "products": ["ZnCl2", "H2O"]},
    {"reactants": ["Cu(OH)2", "HNO3"], "products": ["Cu(NO3)2", "H2O"]},
    {"reactants": ["C", "CuO"], "products": ["Cu", "CO2"]},
    {"reactants": ["C", "H2O"], "products": ["CO", "H2"]},
    {"reactants": ["C", "H2O"], "products": ["CO2", "H2"]},
    {"reactants": ["Al", "H2O"], "products": ["Al(OH)3", "H2"]},
    {"reactants": ["Al", "Fe2O3"], "products": ["Al2O3", "Fe"]},
    {"reactants": ["Al2O3", "NaOH"], "products": ["NaAlO2", "H2O"]},
    {"reactants": ["Al(OH)3", "NaOH"], "products": ["NaAlO2", "H2O"]},
    {"reactants": ["Ca", "H2O"], "products": ["Ca(OH)2", "H2"]},
    {"reactants": ["Ca", "HNO3"], "products": ["Ca(NO3)2", "NH4NO3", "H20"]},
    {"reactants": ["Na", "H2O"], "products": ["NaOH", "H2"]},
    {"reactants": ["NaI", "Br2"], "products": ["NaBr", "I2"]},
    {"reactants": ["KI", "Br2"], "products": ["KBr", "I2"]},
    {"reactants": ["Fe", "H2O"], "products": ["Fe3O4", "H2"]},
    {"reactants": ["Fe", "H2O"], "products": ["FeO", "H2"]},
    {"reactants": ["Fe", "HNO3"], "products": ["Fe(NO3)3", "N20", "H20"]},
    {"reactants": ["Fe(OH)3", "HNO3"], "products": ["Fe(NO3)3", "H20"]},
    {"reactants": ["CO2", "Ca(OH)2"], "products": ["CaCO3", "H2O"]},
    {"reactants": ["NO2", "NaOH"], "products": ["NaNO2", "NaNO2", "H2O"]},
    {"reactants": ["NaCl", "H2SO4"], "products": ["Na2SO4", "HCl "]},
    {"reactants": ["H2S", "Pb(NO3)2"], "products": ["PbS", "HNO3"]},
    {"reactants": ["Na2S", "Pb(NO3)2"], "products": ["PbS", "NaNO3"]},
    {"reactants": ["KNO3", "S", "C"], "products": ["K2S", "N2", "CO2"]},
    {"reactants": ["H2S", "Cl2", "H2O"], "products": ["H2SO4", "HCl"]},
    {"reactants": ["H2SO3", "Cl2", "H2O"], "products": ["H2SO4", "HCl"]},
    {"reactants": ["H2SO3", "Br2", "H2O"], "products": ["H2SO4", "HBr"]},
    {"reactants": ["Fe", "H2O", "O2"], "products": ["Fe(OH)3"]},
    {"reactants": ["FeSO4", "KMnO4", "H2SO4"], "products": ["Fe2(SO4)3", "MnSO4", "K2SO4", "H2O"]},
    {"reactants": ["KClO3"], "products": ["KCl", "O2"]},
    {"reactants": ["KClO3"], "products": ["KCl", "KClO4"]},
    {"reactants": ["HI"], "products": ["H2", "I2"]},
    {"reactants": ["KClO3"], "products": ["KCl", "O2"]},
    {"reactants": ["KMnO4"], "products": ["K2MnO4", "MnO2", "O2"]},
    {"reactants": ["H2O"], "products": ["H2", "O2"]},
    {"reactants": ["Ba(NO3)2", "H2SO4"], "products": ["Ba2SO4", "HNO3"]},
    {"reactants": ["CaCO3"], "products": ["CaO", "CO2"]},
    {"reactants": ["NaNO3"], "products": ["NaNO2", "O2"]},
    {"reactants": ["Al2O3"], "products": ["Al", "O2"]},
    {"reactants": ["Al(OH)3"], "products": ["Al2O3", "H2O"]},
    {"reactants": ["CaCl2"], "products": ["Ca", "Cl2"]},
    {"reactants": ["NaCl"], "products": ["Na", "Cl2"]},
    {"reactants": ["NaOH"], "products": ["Na", "O2", "H20"]},
    {"reactants": ["(NH4)2SO4"], "products": ["NH3", "H2SO4"]},
    {"reactants": ["KMnO4"], "products": ["K2MnO4", "MnO2", "O2"]},
    {"reactants": ["HNO3"], "products": ["NO2", "O2", "H2O"]},
    {"reactants": ["NH4NO2"], "products": ["N2", "H2O"]},
    {"reactants": ["NH4NO3"], "products": ["N2", "O2", "H2O"]},
]
