F = [
{'reactants': {'Na', 'Cl2'}, 'products': {'NaCl'}, 'equation': 'Na + Cl2 → NaCl'},
{'reactants': {'Cl2', 'Fe'}, 'products': {'FeCl3'}, 'equation': 'Fe + Cl2 → FeCl3'},
{'reactants': {'Cu', 'Cl2'}, 'products': {'CuCl2'}, 'equation': 'Cu + Cl2 → CuCl2'},
{'reactants': {'Cl2', 'K'}, 'products': {'KCl'}, 'equation': 'K + Cl2 → KCl'},
{'reactants': {'Na', 'Cl2'}, 'products': {'NaCl'}, 'equation': 'Na + Cl2 → NaCl'},
{'reactants': {'Al', 'Cl2'}, 'products': {'AlCl3'}, 'equation': 'Al + Cl2 → AlCl3'},
{'reactants': {'Ca', 'Cl2'}, 'products': {'CaCl2'}, 'equation': 'Ca + Cl2 → CaCl2'},
{'reactants': {'FeCl2', 'Cl2'}, 'products': {'FeCl3'}, 'equation': 'FeCl2 + Cl2 → FeCl3'},
{'reactants': {'Cl2', 'H2'}, 'products': {'HCl'}, 'equation': 'H2 + Cl2 → HCl'},
{'reactants': {'Br2', 'Al'}, 'products': {'AlBr3'}, 'equation': 'Al + Br2 → AlBr3'},
{'reactants': {'I2', 'Al'}, 'products': {'AlI3'}, 'equation': 'Al + I2 → AlI3'},
{'reactants': {'Br2', 'H2'}, 'products': {'HBr'}, 'equation': 'H2 + Br2 → HBr'},
{'reactants': {'I2', 'H2'}, 'products': {'HI'}, 'equation': 'H2 + I2 → HI'},
{'reactants': {'F2', 'H2'}, 'products': {'HF'}, 'equation': 'H2 + F2 → HF'},
{'reactants': {'Ca', 'O2'}, 'products': {'CaO'}, 'equation': 'Ca + O2 → CaO'},
{'reactants': {'O2', 'Al'}, 'products': {'Al2O3'}, 'equation': 'Al + O2 → Al2O3'},
{'reactants': {'O2', 'Fe'}, 'products': {'Fe2O3'}, 'equation': 'Fe + O2 → Fe2O3'},
{'reactants': {'O2', 'Fe'}, 'products': {'Fe3O4'}, 'equation': 'Fe + O2 → Fe3O4'},
{'reactants': {'O2', 'Fe'}, 'products': {'FeO'}, 'equation': 'Fe + O2 → FeO'},
{'reactants': {'O2', 'Zn'}, 'products': {'ZnO'}, 'equation': 'Zn + O2 → ZnO'},
{'reactants': {'O2', 'Cu'}, 'products': {'CuO'}, 'equation': 'Cu + O2 → CuO'},
{'reactants': {'O2', 'Mg'}, 'products': {'MgO'}, 'equation': 'Mg + O2 → MgO'},
{'reactants': {'O2', 'Na'}, 'products': {'Na2O'}, 'equation': 'Na + O2 → Na2O'},
{'reactants': {'O2', 'K'}, 'products': {'K2O'}, 'equation': 'K + O2 → K2O'},
{'reactants': {'O2', 'S'}, 'products': {'SO2'}, 'equation': 'S + O2 → SO2'},
{'reactants': {'O2', 'SO2'}, 'products': {'SO3'}, 'equation': 'SO2 + O2 → SO3'},
{'reactants': {'O2', 'C'}, 'products': {'CO2'}, 'equation': 'C + O2 → CO2'},
{'reactants': {'O2', 'N2'}, 'products': {'NO'}, 'equation': 'N2 + O2 → NO'},
{'reactants': {'O2', 'H2'}, 'products': {'H2O'}, 'equation': 'H2 + O2 → H2O'},
{'reactants': {'Fe', 'S'}, 'products': {'FeS'}, 'equation': 'Fe + S → FeS'},
{'reactants': {'Zn', 'S'}, 'products': {'ZnS'}, 'equation': 'Zn + S → ZnS'},
{'reactants': {'Cu', 'S'}, 'products': {'CuS'}, 'equation': 'Cu + S → CuS'},
{'reactants': {'S', 'Hg'}, 'products': {'HgS'}, 'equation': 'Hg + S → HgS'},
{'reactants': {'S', 'H2'}, 'products': {'H2S'}, 'equation': 'H2 + S → H2S'},
{'reactants': {'SO2', 'CaO'}, 'products': {'CaSO3'}, 'equation': 'SO2 + CaO → CaSO3'},
{'reactants': {'SO2', 'H2O'}, 'products': {'H2SO3'}, 'equation': 'H2O + SO2 → H2SO3'},
{'reactants': {'SO3', 'H2O'}, 'products': {'H2SO4'}, 'equation': 'SO3 + H2O → H2SO4'},
{'reactants': {'O2', 'SO2'}, 'products': {'SO3'}, 'equation': 'SO2 + O2 → SO3'},
{'reactants': {'SO2', 'H2O'}, 'products': {'H2SO3'}, 'equation': 'SO2 + H2O → H2SO3'},
{'reactants': {'SO2', 'NaOH'}, 'products': {'NaHSO3'}, 'equation': 'SO2 + NaOH → NaHSO3'},
{'reactants': {'N2', 'H2'}, 'products': {'NH3'}, 'equation': 'N2 + H2 → NH3'},
{'reactants': {'H2SO4', 'Fe(OH)3'}, 'products': {'Fe2(SO4)3', 'H2O'}, 'equation': 'Fe(OH)3 + H2SO4 → Fe2(SO4)3 + H2O'},
{'reactants': {'Cl2', 'H2O'}, 'products': {'HCl', 'HClO'}, 'equation': 'Cl2 + H2O → HCl + HClO'},
{'reactants': {'HCl', 'MnO2'}, 'products': {'MnCl2', 'Cl2', 'H2O'}, 'equation': 'MnO2 + HCl → MnCl2 + Cl2 + H2O'},
{'reactants': {'HCl', 'KMnO4'}, 'products': {'MnCl2', 'Cl2', 'KCl', 'H2O'}, 'equation': 'HCl + KMnO4 → KCl + MnCl2 + H2O + Cl2'},
{'reactants': {'NaCl', 'H2O'}, 'products': {'Cl2', 'NaOH', 'H2'}, 'equation': 'NaCl + H2O → Cl2 + H2 + NaOH'},
{'reactants': {'KBr', 'Cl2'}, 'products': {'Br2', 'KCl'}, 'equation': 'Cl2 + KBr → KCl + Br2'},
{'reactants': {'NaBr', 'Cl2'}, 'products': {'Br2', 'NaCl'}, 'equation': 'Cl2 + NaBr → NaCl + Br2'},
{'reactants': {'H2SO4', 'NaCl'}, 'products': {'HCl', 'NaHSO4'}, 'equation': 'NaCl + H2SO4 → NaHSO4 + HCl'},
{'reactants': {'H2SO4', 'KCl'}, 'products': {'HCl', 'KHSO4'}, 'equation': 'KCl + H2SO4 → KHSO4 + HCl'},
{'reactants': {'H2SO4', 'KCl'}, 'products': {'HCl', 'K2SO4'}, 'equation': 'KCl + H2SO4 → K2SO4 + HCl'},
{'reactants': {'H2SO4', 'CaCl2'}, 'products': {'CaSO4', 'HCl'}, 'equation': 'CaCl2 + H2SO4 → CaSO4 + HCl'},
{'reactants': {'H2SO4', 'CaCl2'}, 'products': {'HCl', 'Ca(HSO4)2'}, 'equation': 'CaCl2 + H2SO4 → Ca(HSO4)2 + HCl'},
{'reactants': {'HCl', 'Zn'}, 'products': {'ZnCl2', 'H2'}, 'equation': 'Zn + HCl → ZnCl2 + H2'},
{'reactants': {'HCl', 'Fe'}, 'products': {'FeCl2', 'H2'}, 'equation': 'Fe + HCl → FeCl2 + H2'},
{'reactants': {'HCl', 'Al'}, 'products': {'AlCl3', 'H2'}, 'equation': 'Al + HCl → AlCl3 + H2'},
{'reactants': {'Ca', 'HCl'}, 'products': {'H2', 'CaCl2'}, 'equation': 'Ca + HCl → CaCl2 + H2'},
{'reactants': {'HCl', 'Na'}, 'products': {'NaCl', 'H2'}, 'equation': 'Na + HCl → NaCl + H2'},
{'reactants': {'HCl', 'K'}, 'products': {'KCl', 'H2'}, 'equation': 'K + HCl → KCl + H2'},
{'reactants': {'HCl', 'Mg'}, 'products': {'MgCl2', 'H2'}, 'equation': 'Mg + HCl → MgCl2 + H2'},
{'reactants': {'HCl', 'CuO'}, 'products': {'CuCl2', 'H2O'}, 'equation': 'CuO + HCl → CuCl2 + H2O'},
{'reactants': {'HCl', 'ZnO'}, 'products': {'ZnCl2', 'H2O'}, 'equation': 'ZnO + HCl → ZnCl2 + H2O'},
{'reactants': {'HCl', 'MgO'}, 'products': {'MgCl2', 'H2O'}, 'equation': 'MgO + HCl → MgCl2 + H2O'},
{'reactants': {'HCl', 'MnO2'}, 'products': {'MnCl2', 'Cl2', 'H2O'}, 'equation': 'MnO2 + HCl → MnCl2 + Cl2 + H2O'},
{'reactants': {'HCl', 'Al2O3'}, 'products': {'AlCl3', 'H2O'}, 'equation': 'Al2O3 + HCl → AlCl3 + H2O'},
{'reactants': {'HCl', 'Al(OH)3'}, 'products': {'AlCl3', 'H2O'}, 'equation': 'Al(OH)3 + HCl → AlCl3 + H2O'},
{'reactants': {'HCl', 'NaOH'}, 'products': {'NaCl', 'H2O'}, 'equation': 'NaOH + HCl → NaCl + H2O'},
{'reactants': {'HCl', 'KOH'}, 'products': {'KCl', 'H2O'}, 'equation': 'KOH + HCl → KCl + H2O'},
{'reactants': {'HCl', 'Zn(OH)2'}, 'products': {'ZnCl2', 'H2O'}, 'equation': 'Zn(OH)2 + HCl → ZnCl2 + H2O'},
{'reactants': {'Cu(OH)2', 'HCl'}, 'products': {'CuCl2', 'H2O'}, 'equation': 'Cu(OH)2 + HCl → CuCl2 + H2O'},
{'reactants': {'Cl2', 'KOH'}, 'products': {'KCl', 'KClO3', 'H2O'}, 'equation': 'Cl2 + KOH → KClO3 + KCl + H2O'},
{'reactants': {'Cl2', 'NaOH'}, 'products': {'NaCl', 'NaClO', 'H2O'}, 'equation': 'Cl2 + NaOH → NaClO + NaCl + H2O'},
{'reactants': {'HCl', 'AgNO3'}, 'products': {'HNO3', 'AgCl'}, 'equation': 'AgNO3 + HCl → HNO3 + AgCl'},
{'reactants': {'HCl', 'CaCO3'}, 'products': {'CO2', 'H2O', 'CaCl2'}, 'equation': 'CaCO3 + HCl → CaCl2 + H2O + CO2'},
{'reactants': {'HCl', 'MgCO3'}, 'products': {'MgCl2', 'CO2', 'H2O'}, 'equation': 'MgCO3 + HCl → MgCl2 + H2O + CO2'},
{'reactants': {'HCl', 'BaSO3'}, 'products': {'BaCl2', 'H2SO3'}, 'equation': 'BaSO3 + HCl → BaCl2 + H2SO3'},
{'reactants': {'NaCl', 'AgNO3'}, 'products': {'NaNO3', 'AgCl'}, 'equation': 'AgNO3 + NaCl → NaNO3 + AgCl'},
{'reactants': {'KCl', 'AgNO3'}, 'products': {'AgCl', 'KNO3'}, 'equation': 'AgNO3 + KCl → KNO3 + AgCl'},
{'reactants': {'HClO3', 'H2S'}, 'products': {'H2SO4', 'HCl'}, 'equation': 'H2S + HClO3 → HCl + H2SO4'},
{'reactants': {'Cl2', 'NaOH'}, 'products': {'NaCl', 'NaClO', 'H2O'}, 'equation': 'Cl2 + NaOH → NaCl + NaClO + H2O'},
{'reactants': {'Cl2', 'KOH'}, 'products': {'KClO', 'KCl', 'H2O'}, 'equation': 'Cl2 + KOH → KCl + KClO + H2O'},
{'reactants': {'Cl2', 'KOH'}, 'products': {'KClO3', 'KCl', 'H2O'}, 'equation': 'Cl2 + KOH → KCl + KClO3 + H2O'},
{'reactants': {'Cl2', 'Ca(OH)2'}, 'products': {'CaOCl2', 'H2O'}, 'equation': 'Ca(OH)2 + Cl2 → CaOCl2 + H2O'},
{'reactants': {'Br2', 'NaI'}, 'products': {'NaBr', 'I2'}, 'equation': 'Br2 + NaI → NaBr + I2'},
{'reactants': {'NaBr', 'Cl2'}, 'products': {'Br2', 'NaCl'}, 'equation': 'Cl2 + NaBr → NaCl + Br2'},
{'reactants': {'HF', 'SiO2'}, 'products': {'SiF4', 'H2O'}, 'equation': 'SiO2 + HF → SiF4 + H2O'},
{'reactants': {'F2', 'H2O'}, 'products': {'O2', 'HF'}, 'equation': 'F2 + H2O → HF + O2'},
{'reactants': {'O2', 'NH3'}, 'products': {'H2O', 'NO'}, 'equation': 'NH3 + O2 → NO + H2O'},
{'reactants': {'O2', 'H2S'}, 'products': {'SO2', 'H2O'}, 'equation': 'H2S + O2 → SO2 + H2O'},
{'reactants': {'O2', 'H2S'}, 'products': {'S', 'H2O'}, 'equation': 'H2S + O2 → S + H2O'},
{'reactants': {'CuSO4', 'H2S'}, 'products': {'H2SO4', 'CuS'}, 'equation': 'H2S + CuSO4 → CuS + H2SO4'},
{'reactants': {'HCl', 'FeS'}, 'products': {'FeCl2', 'H2S'}, 'equation': 'FeS + HCl → FeCl2 + H2S'},
{'reactants': {'HCl', 'ZnS'}, 'products': {'ZnCl2', 'H2S'}, 'equation': 'ZnS + HCl → ZnCl2 + H2S'},
{'reactants': {'SO2', 'NaOH'}, 'products': {'Na2SO3', 'H2O'}, 'equation': 'SO2 + NaOH → Na2SO3 + H2O'},
{'reactants': {'SO2', 'H2S'}, 'products': {'S', 'H2O'}, 'equation': 'H2S + SO2 → S + H2O'},
{'reactants': {'O2', 'FeS2'}, 'products': {'SO2', 'Fe2O3'}, 'equation': 'FeS2 + O2 → Fe2O3 + SO2'},
{'reactants': {'O2', 'ZnS'}, 'products': {'ZnO', 'SO2'}, 'equation': 'ZnS + O2 → ZnO + SO2'},
{'reactants': {'O2', 'CuS'}, 'products': {'SO2', 'CuO'}, 'equation': 'CuS + O2 → CuO + SO2'},
{'reactants': {'H2SO4', 'NaOH'}, 'products': {'H2O', 'Na2SO4'}, 'equation': 'NaOH + H2SO4 → Na2SO4 + H2O'},
{'reactants': {'H2SO4', 'KOH'}, 'products': {'K2SO4', 'H2O'}, 'equation': 'KOH + H2SO4 → K2SO4 + H2O'},
{'reactants': {'H2SO4', 'Ba(OH)2'}, 'products': {'H2O', 'BaSO4'}, 'equation': 'Ba(OH)2 + H2SO4 → BaSO4 + H2O'},
{'reactants': {'H2SO4', 'Mg(OH)2'}, 'products': {'MgSO4', 'H2O'}, 'equation': 'Mg(OH)2 + H2SO4 → MgSO4 + H2O'},
{'reactants': {'H2SO4', 'CuO'}, 'products': {'CuSO4', 'H2O'}, 'equation': 'CuO + H2SO4 → CuSO4 + H2O'},
{'reactants': {'H2SO4', 'ZnO'}, 'products': {'ZnSO4', 'H2O'}, 'equation': 'ZnO + H2SO4 → ZnSO4 + H2O'},
{'reactants': {'H2SO4', 'Zn'}, 'products': {'ZnSO4', 'H2'}, 'equation': 'Zn + H2SO4 → ZnSO4 + H2'},
{'reactants': {'H2SO4', 'Fe'}, 'products': {'FeSO4', 'H2'}, 'equation': 'Fe + H2SO4 → FeSO4 + H2'},
{'reactants': {'H2SO4', 'Na'}, 'products': {'H2', 'Na2SO4'}, 'equation': 'Na + H2SO4 → Na2SO4 + H2'},
{'reactants': {'H2SO4', 'K'}, 'products': {'K2SO4', 'H2'}, 'equation': 'K + H2SO4 → K2SO4 + H2'},
{'reactants': {'H2SO4', 'Cu'}, 'products': {'CuSO4', 'SO2', 'H2O'}, 'equation': 'Cu + H2SO4 → CuSO4 + SO2 + H2O'},
{'reactants': {'H2SO4', 'Mg'}, 'products': {'MgSO4', 'S', 'H2O'}, 'equation': 'Mg + H2SO4 → MgSO4 + S + H2O'},
{'reactants': {'H2SO4', 'C'}, 'products': {'SO2', 'CO2', 'H2O'}, 'equation': 'C + H2SO4 → CO2 + SO2 + H2O'},
{'reactants': {'H2SO4', 'CaCO3'}, 'products': {'CaSO4', 'CO2', 'H2O'}, 'equation': 'CaCO3 + H2SO4 → CaSO4 + H2O + CO2'},
{'reactants': {'H2SO4', 'K2CO3'}, 'products': {'K2SO4', 'CO2', 'H2O'}, 'equation': 'K2CO3 + H2SO4 → K2SO4 + H2O + CO2'},
{'reactants': {'H2SO4', 'H2S'}, 'products': {'SO2', 'S', 'H2O'}, 'equation': 'H2SO4 + H2S → S + SO2 + H2O'},
{'reactants': {'H2SO4', 'BaCl2'}, 'products': {'HCl', 'BaSO4'}, 'equation': 'H2SO4 + BaCl2 → BaSO4 + HCl'},
{'reactants': {'BaCl2', 'Na2SO4'}, 'products': {'NaCl', 'BaSO4'}, 'equation': 'Na2SO4 + BaCl2 → BaSO4 + NaCl'},
{'reactants': {'Na2SO3', 'BaCl2'}, 'products': {'NaCl', 'BaSO3'}, 'equation': 'Na2SO3 + BaCl2 → BaSO3 + NaCl'},
{'reactants': {'K2SO4', 'BaCl2'}, 'products': {'KCl', 'BaSO4'}, 'equation': 'K2SO4 + BaCl2 → BaSO4 + KCl'},
{'reactants': {'K2SO3', 'BaCl2'}, 'products': {'Kcl', 'BaSO3'}, 'equation': 'K2SO3 + BaCl2 → BaSO3 + Kcl'},
{'reactants': {'KCl', 'Na2SO4'}, 'products': {'K2SO4', 'NaCl'}, 'equation': 'Na2SO4 + KCl → K2SO4 + NaCl'},
{'reactants': {'CuSO4', 'Fe'}, 'products': {'FeSO4', 'Cu'}, 'equation': 'Fe + CuSO4 → FeSO4 + Cu'},
{'reactants': {'CuSO4', 'Zn'}, 'products': {'ZnSO4', 'Cu'}, 'equation': 'Zn + CuSO4 → ZnSO4 + Cu'},
{'reactants': {'CuSO4', 'KOH'}, 'products': {'Cu(OH)2', 'K2SO4'}, 'equation': 'CuSO4 + KOH → Cu(OH)2 + K2SO4'},
{'reactants': {'CuSO4', 'NaOH'}, 'products': {'Cu(OH)2', 'Na2SO4'}, 'equation': 'CuSO4 + NaOH → Cu(OH)2 + Na2SO4'},
{'reactants': {'H2SO4', 'Zn'}, 'products': {'ZnSO4', 'S', 'H2O'}, 'equation': 'Zn + H2SO4 → ZnSO4 + S + H2O'},
{'reactants': {'H2SO4', 'Mg'}, 'products': {'H2S', 'MgSO4', 'H2O'}, 'equation': 'Mg + H2SO4 → MgSO4 + H2S + H2O'},
{'reactants': {'Ag', 'H2SO4'}, 'products': {'SO2', 'Ag2SO4', 'H2O'}, 'equation': 'Ag + H2SO4 → Ag2SO4 + SO2 + H2O'},
{'reactants': {'H2SO4', 'S'}, 'products': {'SO2', 'H2O'}, 'equation': 'S + H2SO4 → SO2 + H2O'},
{'reactants': {'O2', 'FeS2'}, 'products': {'SO2', 'Fe2O3'}, 'equation': 'FeS2 + O2 → Fe2O3 + SO2'},
{'reactants': {'H2SO4', 'Na2SO3'}, 'products': {'SO2', 'H2O', 'Na2SO4'}, 'equation': 'Na2SO3 + H2SO4 → Na2SO4 + H2O + SO2'},
{'reactants': {'H2SO4', 'Na2CO3'}, 'products': {'CO2', 'H2O', 'Na2SO4'}, 'equation': 'Na2CO3 + H2SO4 → Na2SO4 + H2O + CO2'},
{'reactants': {'CuO', 'H2'}, 'products': {'Cu', 'H2O'}, 'equation': 'H2 + CuO → Cu + H2O'},
{'reactants': {'ZnO', 'H2'}, 'products': {'Zn', 'H2O'}, 'equation': 'H2 + ZnO → Zn + H2O'},
{'reactants': {'Fe2O3', 'H2'}, 'products': {'Fe', 'H2O'}, 'equation': 'Fe2O3 + H2 → Fe + H2O'},
{'reactants': {'HCl', 'Zn(OH)2'}, 'products': {'ZnCl2', 'H2O'}, 'equation': 'Zn(OH)2 + HCl → ZnCl2 + H2O'},
{'reactants': {'Cu(OH)2', 'HNO3'}, 'products': {'Cu(NO3)2', 'H2O'}, 'equation': 'Cu(OH)2 + HNO3 → Cu(NO3)2 + H2O'},
{'reactants': {'C', 'CuO'}, 'products': {'Cu', 'CO2'}, 'equation': 'C + CuO → Cu + CO2'},
{'reactants': {'C', 'H2O'}, 'products': {'H2', 'CO'}, 'equation': 'C + H2O → CO + H2'},
{'reactants': {'C', 'H2O'}, 'products': {'CO2', 'H2'}, 'equation': 'C + H2O → CO2 + H2'},
{'reactants': {'Al', 'H2O'}, 'products': {'Al(OH)3', 'H2'}, 'equation': 'Al + H2O → Al(OH)3 + H2'},
{'reactants': {'Al', 'Fe2O3'}, 'products': {'Al2O3', 'Fe'}, 'equation': 'Al + Fe2O3 → Al2O3 + Fe'},
{'reactants': {'Al2O3', 'NaOH'}, 'products': {'NaAlO2', 'H2O'}, 'equation': 'Al2O3 + NaOH → NaAlO2 + H2O'},
{'reactants': {'NaOH', 'Al(OH)3'}, 'products': {'NaAlO2', 'H2O'}, 'equation': 'Al(OH)3 + NaOH → NaAlO2 + H2O'},
{'reactants': {'Ca', 'H2O'}, 'products': {'H2', 'Ca(OH)2'}, 'equation': 'Ca + H2O → Ca(OH)2 + H2'},
{'reactants': {'Ca', 'HNO3'}, 'products': {'NH4NO3', 'H20', 'Ca(NO3)2'}, 'equation': 'Ca + HNO3 → Ca(NO3)2 + NH4NO3 + H20'},
{'reactants': {'Na', 'H2O'}, 'products': {'NaOH', 'H2'}, 'equation': 'Na + H2O → NaOH + H2'},
{'reactants': {'Br2', 'NaI'}, 'products': {'NaBr', 'I2'}, 'equation': 'NaI + Br2 → NaBr + I2'},
{'reactants': {'Br2', 'KI'}, 'products': {'KBr', 'I2'}, 'equation': 'KI + Br2 → KBr + I2'},
{'reactants': {'Fe', 'H2O'}, 'products': {'Fe3O4', 'H2'}, 'equation': 'Fe + H2O → Fe3O4 + H2'},
{'reactants': {'Fe', 'H2O'}, 'products': {'FeO', 'H2'}, 'equation': 'Fe + H2O → FeO + H2'},
{'reactants': {'HNO3', 'Fe'}, 'products': {'N20', 'Fe(NO3)3', 'H20'}, 'equation': 'Fe + HNO3 → Fe(NO3)3 + N20 + H20'},
{'reactants': {'HNO3', 'Fe(OH)3'}, 'products': {'Fe(NO3)3', 'H20'}, 'equation': 'Fe(OH)3 + HNO3 → Fe(NO3)3 + H20'},
{'reactants': {'CO2', 'Ca(OH)2'}, 'products': {'CaCO3', 'H2O'}, 'equation': 'CO2 + Ca(OH)2 → CaCO3 + H2O'},
{'reactants': {'NO2', 'NaOH'}, 'products': {'NaNO2', 'H2O'}, 'equation': 'NO2 + NaOH → NaNO2 + NaNO2 + H2O'},
{'reactants': {'H2SO4', 'NaCl'}, 'products': {'HCl ', 'Na2SO4'}, 'equation': 'NaCl + H2SO4 → Na2SO4 + HCl '},
{'reactants': {'Pb(NO3)2', 'H2S'}, 'products': {'HNO3', 'PbS'}, 'equation': 'H2S + Pb(NO3)2 → PbS + HNO3'},
{'reactants': {'Na2S', 'Pb(NO3)2'}, 'products': {'NaNO3', 'PbS'}, 'equation': 'Na2S + Pb(NO3)2 → PbS + NaNO3'},
{'reactants': {'C', 'KNO3', 'S'}, 'products': {'K2S', 'N2', 'CO2'}, 'equation': 'KNO3 + S + C → K2S + N2 + CO2'},
{'reactants': {'H2S', 'H2O', 'Cl2'}, 'products': {'H2SO4', 'HCl'}, 'equation': 'H2S + Cl2 + H2O → H2SO4 + HCl'},
{'reactants': {'Cl2', 'H2O', 'H2SO3'}, 'products': {'H2SO4', 'HCl'}, 'equation': 'H2SO3 + Cl2 + H2O → H2SO4 + HCl'},
{'reactants': {'Br2', 'H2O', 'H2SO3'}, 'products': {'H2SO4', 'HBr'}, 'equation': 'H2SO3 + Br2 + H2O → H2SO4 + HBr'},
{'reactants': {'O2', 'Fe', 'H2O'}, 'products': {'Fe(OH)3'}, 'equation': 'Fe + H2O + O2 → Fe(OH)3'},
{'reactants': {'FeSO4', 'H2SO4', 'KMnO4'}, 'products': {'Fe2(SO4)3', 'K2SO4', 'H2O', 'MnSO4'}, 'equation': 'FeSO4 + KMnO4 + H2SO4 → Fe2(SO4)3 + MnSO4 + K2SO4 + H2O'},
{'reactants': {'KClO3'}, 'products': {'O2', 'KCl'}, 'equation': 'KClO3 → KCl + O2'},
{'reactants': {'KClO3'}, 'products': {'KCl', 'KClO4'}, 'equation': 'KClO3 → KCl + KClO4'},
{'reactants': {'HI'}, 'products': {'I2', 'H2'}, 'equation': 'HI → H2 + I2'},
{'reactants': {'KMnO4'}, 'products': {'O2', 'K2MnO4', 'MnO2'}, 'equation': 'KMnO4 → K2MnO4 + MnO2 + O2'},
{'reactants': {'H2O'}, 'products': {'O2', 'H2'}, 'equation': 'H2O → H2 + O2'},
{'reactants': {'H2SO4', 'Ba(NO3)2'}, 'products': {'Ba2SO4', 'HNO3'}, 'equation': 'Ba(NO3)2 + H2SO4 → Ba2SO4 + HNO3'},
{'reactants': {'CaCO3'}, 'products': {'CaO', 'CO2'}, 'equation': 'CaCO3 → CaO + CO2'},
{'reactants': {'NaNO3'}, 'products': {'O2', 'NaNO2'}, 'equation': 'NaNO3 → NaNO2 + O2'},
{'reactants': {'Al2O3'}, 'products': {'O2', 'Al'}, 'equation': 'Al2O3 → Al + O2'},
{'reactants': {'Al(OH)3'}, 'products': {'Al2O3', 'H2O'}, 'equation': 'Al(OH)3 → Al2O3 + H2O'},
{'reactants': {'CaCl2'}, 'products': {'Ca', 'Cl2'}, 'equation': 'CaCl2 → Ca + Cl2'},
{'reactants': {'NaCl'}, 'products': {'Na', 'Cl2'}, 'equation': 'NaCl → Na + Cl2'},
{'reactants': {'NaOH'}, 'products': {'O2', 'Na', 'H20'}, 'equation': 'NaOH → Na + O2 + H20'},
{'reactants': {'(NH4)2SO4'}, 'products': {'H2SO4', 'NH3'}, 'equation': '(NH4)2SO4 → NH3 + H2SO4'},
{'reactants': {'KMnO4'}, 'products': {'O2', 'K2MnO4', 'MnO2'}, 'equation': 'KMnO4 → K2MnO4 + MnO2 + O2'},
{'reactants': {'HNO3'}, 'products': {'O2', 'NO2', 'H2O'}, 'equation': 'HNO3 → NO2 + O2 + H2O'},
{'reactants': {'NH4NO2'}, 'products': {'N2', 'H2O'}, 'equation': 'NH4NO2 → N2 + H2O'},
{'reactants': {'NH4NO3'}, 'products': {'O2', 'N2', 'H2O'}, 'equation': 'NH4NO3 → N2 + O2 + H2O'}
]